# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202208

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)
print(f"A:\n{A}")
print(f"B:\n{B}")
print(f"C:\n{C}")

print("---")
# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

A:
[[-0.06717552 -1.4918898   1.41238729  1.00741706]
 [-0.00759516 -0.59167253  0.83022673 -0.26903079]
 [ 0.13170851  0.49993185  0.92721284 -0.8732846 ]]
B:
[[ 0.69461057 -0.41142934  0.33000103 -1.72953985 -0.10282281]
 [ 0.15786945 -0.32225079 -0.8057044  -1.58082965  0.24625925]
 [ 0.52826581 -0.43568159  0.62082182  0.11086843 -0.33731607]
 [ 0.34714741  2.65527638 -1.00084539 -0.11629043 -0.24868848]]
C:
[[-0.85798869  0.13346523  0.44086168 -0.86178659  1.79206987  0.00335218
   0.17783197]
 [ 0.77592693 -1.08603745  1.27339558  0.68029091  0.69339412 -1.52689225
   0.33268579]
 [-0.36681595  0.61478605 -1.25328385  0.5907718  -1.30943125 -0.05521753
  -0.81435137]]
---
[[ 0.81  2.57  1.05  2.51 -1.09]
 [ 0.25 -0.88  1.26  1.07 -0.36]
 [ 0.36 -2.94  1.09 -0.81  0.01]]
 
[[ 0.    0.64 -0.91 -0.75]
 [ 0.08  0.75 -0.14 -0.11]
 [-0.2  -2.04  0.52  1.2 ]
 [ 0.13  1.18 -0.1  -1.57]
 [-0.3  -3.74  1.89  2.76]
 [ 0.    0.87 -1.31  0.46]
 [-0.12 -0.87 -0.23  0.8 ]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )
print(f"A:\n{A}")
print(f"B:\n{B}")
print(f"C1:\n{C1}")
print(f"C2:\n{C2}")
print('---')
# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

A:
tensor([[ 0.8975,  0.5192,  1.1124, -0.3907],
        [-1.5952,  0.2843, -0.4526, -1.1970],
        [ 0.2424,  0.4207,  1.0488,  0.2770]])
B:
tensor([[-0.4105,  1.3904, -1.0412,  0.8428,  0.3614],
        [ 1.3542,  0.4015,  0.0163,  1.7252,  0.1814],
        [-1.6497,  1.5920, -0.0020, -1.1535, -1.0811],
        [-0.2957,  0.4150,  0.1269, -0.0683,  0.7280]])
C1:
[[-0.33344521  0.9103774   0.61419556 -0.67693005 -0.86138152 -0.88400646
  -0.8184503 ]
 [ 0.1656954   0.05127111 -0.62629674  1.31800693 -1.07257864  1.92519282
   1.07485712]
 [ 0.42925046 -1.98122841  1.42580207  2.26825365  0.34512912 -0.1191833
   0.41048764]
 [ 0.43161267  0.80625327 -0.50549745  0.10925436 -1.83287224  0.27839104
   0.63744305]]
C2:
tensor([[-0.3334,  0.9104,  0.6142, -0.6769, -0.8614, -0.8840, -0.8185],
        [ 0.1657,  0.0513, -0.6263,  1.3180, -1.0726,  1.9252,  1.0749],
        [ 0.4293, -1.9812,  1.4258,  2.2683,  0.3451, -0.1192,  0.4105],
        [ 0.4316,  0.8063, -0.5055,  0.1093, -1.832