# COURSE: A deep understanding of deep learning
## SECTION: Data matrices and loaders
### LECTURE: Anatomy of a torch dataset and dataloader
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202208

In [3]:
# import libraries
import numpy as np
import torch
from torch.utils.data import DataLoader,TensorDataset

# Datasets

In [4]:
# create some data in numpy

nObservations = 100
nFeatures = 20

data = np.random.randn(nObservations,nFeatures)

In [5]:
# Convert to pytorch tensor
dataT = torch.tensor( data ) 

# print out some information
print('Numpy data:')
print(type(data))
print(data.shape) # numpy -> .shape
print(data.dtype)
print(' ')

print('Tensor data:')
print(type(dataT))
print(dataT.size()) # torch -> .size()
print(dataT.dtype)
print(' ')

Numpy data:
<class 'numpy.ndarray'>
(100, 20)
float64
 
Tensor data:
<class 'torch.Tensor'>
torch.Size([100, 20])
torch.float64
 


In [6]:
# Sometimes you need to convert data types

dataT2 = torch.tensor( data ).float()
print(dataT2.dtype)

# "long" is for ints
dataT3 = torch.tensor( data ).long()
print(dataT3.dtype)


torch.float32
torch.int64


In [7]:
# Convert tensor into PyTorch Datasets

# dataset = TensorDataset(data) # not a tensor!
dataset = TensorDataset(dataT)

# dataset is a two-element tuple comprising data,labels
dataset.tensors[0]

tensor([[-0.9323,  1.1561,  1.0616,  ..., -0.8966,  1.4696,  0.9193],
        [ 0.7976, -0.2768,  0.8884,  ..., -0.5989, -0.7664, -0.9267],
        [ 0.0928, -2.2695, -1.9513,  ..., -0.6310,  0.7943,  0.2690],
        ...,
        [-1.3419,  0.0848, -2.3496,  ..., -0.4513, -0.9443, -1.9523],
        [ 0.1848, -0.9677, -0.1577,  ..., -1.2270,  0.6828,  0.8147],
        [ 1.5279, -2.0171, -1.2804,  ...,  0.0087, -0.6283,  1.2585]],
       dtype=torch.float64)

In [ ]:
# Let's try again with labels
labels = torch.ceil(torch.linspace(.01,4,nObservations))
print(f"labels: {labels}")
print("---")
# transform to an actual matrix (column vector)
labels = labels.reshape(( len(labels),1 ))
print( labels )
print(f"labels: {labels}")
print("---")
# now make another dataset
dataset = TensorDataset(dataT,labels)
print( dataset.tensors[0].size() )
print( dataset.tensors[1].size() )

# for comparison
print( np.shape(np.random.randint(5,size=nObservations)) )

# DataLoaders

In [19]:
# create a dataloader object
batchsize = 25
dataloader = DataLoader(dataset,batch_size=batchsize)#,shuffle=True,drop_last=True)

dataloader.dataset.tensors[0].size()

torch.Size([100, 20])

In [20]:
# sizes of each batch
for dat,labs in dataloader:
  print('BATCH INFO:')
  print(dat.size())
  print(labs.size())
  print(' ')

BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 
BATCH INFO:
torch.Size([25, 20])
torch.Size([25, 1])
 


In [21]:
# inspect the labels
for dat,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
         1., 1., 1., 1., 1., 1., 1.]])
 
tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
         2., 2., 2., 2., 2., 2., 2.]])
 
tensor([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
         3., 3., 3., 3., 3., 3., 3.]])
 
tensor([[4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4., 4.,
         4., 4., 4., 4., 4., 4., 4.]])
 


In [24]:
# try again with shuffling (shuffling happens during iterations)
dataloader = DataLoader(dataset,batch_size=batchsize,shuffle=True)

for dat,labs in dataloader:
  print(labs.T)
  print(' ')

tensor([[2., 4., 2., 4., 3., 4., 4., 3., 3., 2., 3., 4., 2., 3., 1., 3., 1., 1.,
         1., 2., 2., 4., 4., 4., 3.]])
 
tensor([[3., 1., 3., 1., 2., 2., 1., 4., 4., 2., 1., 3., 2., 1., 2., 1., 2., 3.,
         2., 1., 4., 2., 2., 4., 4.]])
 
tensor([[1., 4., 4., 3., 4., 3., 2., 4., 3., 2., 2., 4., 2., 2., 4., 1., 3., 1.,
         2., 3., 2., 1., 3., 2., 1.]])
 
tensor([[3., 4., 4., 4., 1., 4., 2., 1., 4., 4., 1., 3., 2., 3., 3., 1., 1., 1.,
         1., 3., 1., 1., 3., 3., 3.]])
 


In [13]:
# To get only one batch (e.g., for testing)

dat,labs = next(iter(dataloader))

labs

tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])