# COURSE: A deep understanding of deep learning
## SECTION: ANNs
### LECTURE: Depth vs. breadth: number of parameters
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/dudl/?couponCode=202208

In [1]:
# import libraries
import numpy as np
import torch
import torch.nn as nn

In [2]:
# build two models

widenet = nn.Sequential(
    nn.Linear(2,4),  # hidden layer
    nn.Linear(4,3),  # output layer
    )


deepnet = nn.Sequential(
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,2),  # hidden layer
    nn.Linear(2,3),  # output layer
    )

# print them out to have a look
print(widenet)
print(' ')
print(deepnet)

Sequential(
  (0): Linear(in_features=2, out_features=4, bias=True)
  (1): Linear(in_features=4, out_features=3, bias=True)
)
 
Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)


In [3]:
# widenet.

# Peeking inside the network

In [4]:
deepnet.named_parameters

<bound method Module.named_parameters of Sequential(
  (0): Linear(in_features=2, out_features=2, bias=True)
  (1): Linear(in_features=2, out_features=2, bias=True)
  (2): Linear(in_features=2, out_features=3, bias=True)
)>

In [18]:
# check out the parameters
for p in deepnet.named_parameters():
  print(p)
  print(' ')

('0.weight', Parameter containing:
tensor([[ 0.2056,  0.2853],
        [-0.5151, -0.2933]], requires_grad=True))
 
('0.bias', Parameter containing:
tensor([ 0.1470, -0.6032], requires_grad=True))
 
('1.weight', Parameter containing:
tensor([[-0.6583,  0.1720],
        [-0.4840,  0.1831]], requires_grad=True))
 
('1.bias', Parameter containing:
tensor([-0.2326, -0.1041], requires_grad=True))
 
('2.weight', Parameter containing:
tensor([[-0.3031,  0.5489],
        [ 0.5400, -0.4717],
        [-0.0565,  0.5138]], requires_grad=True))
 
('2.bias', Parameter containing:
tensor([ 0.4719,  0.6858, -0.4455], requires_grad=True))
 


In [19]:
for i in deepnet.named_parameters():
    print(type(i[0]))
    print('---')
    print(type(i[1]))
    print("------------")
    print(i[0])
    print('---')
    print(i[1].detach()) # これで重み情報のみ抜き取れる
    print("============================")

<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
0.weight
---
tensor([[ 0.2056,  0.2853],
        [-0.5151, -0.2933]])
<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
0.bias
---
tensor([ 0.1470, -0.6032])
<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
1.weight
---
tensor([[-0.6583,  0.1720],
        [-0.4840,  0.1831]])
<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
1.bias
---
tensor([-0.2326, -0.1041])
<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
2.weight
---
tensor([[-0.3031,  0.5489],
        [ 0.5400, -0.4717],
        [-0.0565,  0.5138]])
<class 'str'>
---
<class 'torch.nn.parameter.Parameter'>
------------
2.bias
---
tensor([ 0.4719,  0.6858, -0.4455])


In [27]:
# named_parameter以外にもparametersというオブジェクトもあり。こっちのほうがシンプル
for i in deepnet.parameters():
     print(i)
     print(f"This returns num of elements: {i.numel()}")
     print('---')

Parameter containing:
tensor([[ 0.2056,  0.2853],
        [-0.5151, -0.2933]], requires_grad=True)
This returns num of elements: 4
---
Parameter containing:
tensor([ 0.1470, -0.6032], requires_grad=True)
This returns num of elements: 2
---
Parameter containing:
tensor([[-0.6583,  0.1720],
        [-0.4840,  0.1831]], requires_grad=True)
This returns num of elements: 4
---
Parameter containing:
tensor([-0.2326, -0.1041], requires_grad=True)
This returns num of elements: 2
---
Parameter containing:
tensor([[-0.3031,  0.5489],
        [ 0.5400, -0.4717],
        [-0.0565,  0.5138]], requires_grad=True)
This returns num of elements: 6
---
Parameter containing:
tensor([ 0.4719,  0.6858, -0.4455], requires_grad=True)
This returns num of elements: 3
---


In [20]:
# count the number of nodes ( = the number of biases)

# named_parameters() is an iterable that returns the tuple (name,numbers)
numNodesInWide = 0
for p in widenet.named_parameters():
  if 'bias' in p[0]:
    numNodesInWide += len(p[1])

numNodesInDeep = 0
for paramName,paramVect in deepnet.named_parameters():
  if 'bias' in paramName:
    numNodesInDeep += len(paramVect)


print('There are %s nodes in the wide network.' %numNodesInWide)
print('There are %s nodes in the deep network.' %numNodesInDeep)

There are 7 nodes in the wide network.
There are 7 nodes in the deep network.


In [21]:
# just the parameters
for p in widenet.parameters():
  print(p)
  print(' ')

Parameter containing:
tensor([[-0.0037, -0.3176],
        [-0.0699,  0.4527],
        [ 0.0812,  0.5526],
        [-0.0915,  0.1432]], requires_grad=True)
 
Parameter containing:
tensor([0.3490, 0.0007, 0.0807, 0.1079], requires_grad=True)
 
Parameter containing:
tensor([[-0.0577, -0.0219,  0.1564, -0.1371],
        [-0.3563, -0.3635,  0.1628,  0.4315],
        [-0.0107,  0.3443,  0.4240,  0.2171]], requires_grad=True)
 
Parameter containing:
tensor([-0.4333,  0.3077,  0.2119], requires_grad=True)
 


In [ ]:
# now count the total number of trainable parameters
nparams = 0
for p in widenet.parameters():
  if p.requires_grad:
    print('This piece has %s parameters' %p.numel())
    nparams += p.numel()

print('\n\nTotal of %s parameters'%nparams)

This piece has 8 parameters
This piece has 4 parameters
This piece has 12 parameters
This piece has 3 parameters


Total of 27 parameters


In [ ]:
# btw, can also use list comprehension

nparams = np.sum([ p.numel() for p in widenet.parameters() if p.requires_grad ])
print('Widenet has %s parameters'%nparams)

nparams = np.sum([ p.numel() for p in deepnet.parameters() if p.requires_grad ])
print('Deepnet has %s parameters'%nparams)

Widenet has 27 parameters
Deepnet has 21 parameters


In [ ]:
# A nice simple way to print out the model info.
from torchsummary import summary
summary(widenet,(1,2))


### NOTE ABOUT THE CODE IN THIS CELL:
# torchsummary is being replaced by torchinfo.
# If you are importing these libraries on your own (via pip), then see the following website:
#        https://pypi.org/project/torch-summary/
# However, torchsummary will continue to be supported, so if the code in this cell works (meaning torchsummary is already installed), 
# then you don't need to do anything!

----------------------------------------------------------------
        Layer (type)               Output Shape         Param #
            Linear-1                 [-1, 1, 4]              12
            Linear-2                 [-1, 1, 3]              15
Total params: 27
Trainable params: 27
Non-trainable params: 0
----------------------------------------------------------------
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
----------------------------------------------------------------


In [ ]:
summary??